name: zendesk_messaging
description: Zendesk-Messaging for Flutter developer
version: 2.9.0
homepage: https://github.com/chyiiiiiiiiiiii/flutter_zendesk_messaging

topics:
  - zendesk
  - custom
  - support
  - help
  - chat

screenshots:
  - description: "Zendesk Messaging"
    path: Messaging.png

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.chyiiiiiiiiiiiiii.zendesk_messaging
        pluginClass: ZendeskMessagingPlugin
      ios:
        pluginClass: ZendeskMessagingPlugin
